services:
  order-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-system
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:sqlite:/data/orders.db
    volumes:
      - ./data:/data
